### ISSUE TITLE
How many WebSocket can open per one server ?

### ISSUE THREAD

**Issue by pedro0606** [cdnbye/cbsignal#1]
How many WebSocket can open per one server ?
How to check numbler of WebSocket ?

**Comment by snowinszu** [comment]
About 250,000 connections per server with 16GB memory. You can check number by requesting http://doamin.com/count

**Comment by pedro0606** [comment]
How many CPU Core for 250,000 cons ?
1 threat ?

**Comment by snowinszu** [comment]
2
