### ISSUE TITLE
Some pakage not found

### ISSUE THREAD

**Issue by pedro0606** [cdnbye/cbsignal#2]
I build on ubuntu 18.04
How to fix ?
------build signaler--------
GOOS=linux GOARCH=amd64 go build -o cbsignal -v main.go
main.go:5:2: **cannot find package "cbsignal/client"** in any of:
	/usr/lib/go-1.10/src/cbsignal/client (from $GOROOT)
	/root/go/src/cbsignal/client (from $GOPATH)
main.go:6:2: **cannot find package "cbsignal/handler**" in any of:
	/usr/lib/go-1.10/src/cbsignal/handler (from $GOROOT)
	/root/go/src/cbsignal/handler (from $GOPATH)
main.go:7:2: **cannot find package "cbsignal/hub"** in any of:
	/usr/lib/go-1.10/src/cbsignal/hub (from $GOROOT)
	/root/go/src/cbsignal/hub (from $GOPATH)
Makefile:15: recipe for target 'main' failed

**Comment by snowinszu** [comment]
Modify $GOPATH, it should be the same directory path as src.
